version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - springboot-mongo-network

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_app_container
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/retaildb
    networks:
      - springboot-mongo-network

volumes:
  mongodb_data:

networks:
  springboot-mongo-network:
    driver: bridge
